version: '3.7'
services:
  frontend:
    build: ./packages/admin_front
    ports:
      - "8000:8000"
    networks:
      - umiadmin
      
  backend:
    build: ./packages/admin_back
    ports:
      - "1101:1101"
    depends_on:
      - mysql
    networks:
      - umiadmin

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=umiadmin
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
      - /path/to/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - umiadmin

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /path/to/redis/data:/data
    command: redis-server --requrepass Lbq17607384217
    networks:
      - umiadmin
networks:
  umiadmin: