export const permmsionList = [
    {
        code:1000,
        name:'首页',
        children:[
            {
                code:100001,
                name:'新建文章标签',
            },
            {
                code:100002,
                name:'删除文章标签',
            },
            {
                code:100003,
                name:'编辑文章标签',
            },
            {
                code:100004,
                name:'新建文章类别',
            },
            {
                code:100005,
                name:'删除文章类别',
            },
            {
                code:100006,
                name:'编辑文章类别',
            },
        ]
    },
    {
        code:1001,
        name:'文章',
        children:[
            {
                code:100101,
                name:'写文章',
            },
            {
                code:100102,
                name:'编辑',
            },
            {
                code:100103,
                name:'删除',
            },
        ]
    },
    {
        code:1002,
        name:'关于',
    }, 
    {
        code:1003,
        name:'留言',
        children:[
            {
                code:100301,
                name:'查看'
            },
            {
                code:100302,
                name:'删除'
            }
        ]
    },
    {
        code:1004,
        name:'图库',
        children:[
            {
                code:100401,
                name:'新增图库'
            },
            {
                code:100402,
                name:'更新'
            },
            {
                code:100403,
                name:'删除'
            },
        ]
    }, 
    {
        code:1005,
        name:'图表'
    },
    {
        code: 1006,
        name:'首页轮播编辑',
        children:[
            {
                code:100601,
                name:'删除'
            },
            {
                code:100602,
                name:'保存'
            },
            {
                code:100603,
                name:'切换'
            },
        ]
    }
]